#!/usr/bin/env bash

commit_regex='^((build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test)(\([a-zA-Z0-9 /_,.-]+?\))?: .{1,79}\w|Merge branch .+|(fixup|squash)! .+)$'

error_msg='
----------------------------------------------------
ABORTING commit - Expecting a conventional commit message header: 
    
      <type>[(optional scope)]: <summary - MAX 80 chars>
----------------------------------------------------
Examples:
1.
  fix(cache): Fixe nasty caching bug (#123)
2.  
  feat: Enable awesome feature (#456)
3. 
  docs: Add instructions to README
----------------------------------------------------
Accepted Types:
  fix       - for fixes (creates PATCH release)
  feat      - for features (creates MINOR release)
  docs      - for documentation changes
  build     - for changes that affect the build or external dependencies
  ci        - for changes related to the ci pipeline
  chore     - for general maintenance changes
  perf      - for performance related changes
  refactor  - for refactoring
  revert    - for revert commits
  style     - for style changes
  test      - for adding or updating tests
----------------------------------------------------
Exceptions:
  fixup! ... 
  squash! ...
  Merge branch ...
'

if ! grep -iqE "${commit_regex}" "$1"; then
    echo "${error_msg}" >&2
    exit 1
fi